### ISSUE TITLE
Search on name / email

### ISSUE THREAD

**Issue by markrrr** [mikebharris/BAMS#5]
This is a feature request for a change in workflow, so when we're looking for an attendee who doesn't know their auth code (that's everyone btw), we don't have to page through the list of all attendees to find them.

Paging through everyone is tedious, but more importantly, we shouldn't really be displaying all those details on the console because people probably don't want every other attendee to see their credentials.

Adding the ability to search on email or realname would make this unnecessary.

The new workflow could be home screen > F2 to search > enter either authcode / realname/ email > display matching record or 'no results found'.

This would require a check for collisions in realname / email at the point of registration

**Comment by mikebharris** [comment]
I've added this ability.  You now go to the search screen and press F5, F6 or F7 to choose to search by AuthCode, Name or Email.  It then takes you straight to the Edit screen if the record is found.

Possible issues.  As the data file is now keyed on the name and email, this currently have to be exact case-sensitive string matches.  Also it is entirely possible that two people have the same name, especially if they only use their first name to sign up.

Longer term, I think it would be better to load the entire data file into a table and then search this table; this should give more flexibility and remove the case-sensitive.  

The other option is to CAPITALISE everything, just like in the old days ;)

**Comment by mikebharris** [comment]
Implemented improved version of this in BAMS 2.0
