### ISSUE TITLE
skip view, go straight to edit

### ISSUE THREAD

**Issue by markrrr** [mikebharris/BAMS#6]
There are hardly any situations in which we need to view a record without editing it, so we can save a step from the flow by going straight into the 'edit' screen each time a record is accessed.

**Comment by mikebharris** [comment]
Done.  Home screen now has F4 Edit, which takes user to Search for an attendee, then once selected straight to the Edit screen.
Commit # a0662fa179a074d0280de3b3d402875a0d6e530e
